name: Java CI with Maven

on:
  push:
    branches: 
      - master
      - config-server

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: cd config-server/;mvn -B package --file pom.xml
